name: Docker Runner

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: self-hosted
    #environment: production eeeeeeeeeeee 3
    permissions: read-all

    steps:
      - uses: actions/checkout@v3

      - name: Pull from repository
        run: git pull --force

      - name: Run Container
        run: docker compose up -d --build
        env:
          TOKEN: ${{ secrets.DISCORD_TOKEN }}

      - name: Cleanup Unused Images
        run: docker image prune -f
