name: Docker Runner

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: self-hosted
    #environment: production
    permissions: read-all

    steps:
      #- uses: actions/checkout@v2

      - name: kys kys kys kys kys
        run: cd

      - name: fucking kill yourself die die die die die die
        run: cd MaldaBot

      - name: Pull from repository
        run: git pull --force

      - name: Run Container
        run: docker compose up -d --build
        env:
          TOKEN: ${{ secrets.DISCORD_TOKEN }}

      - name: Cleanup Unused Images
        run: docker image prune -f