name: Docker Runner

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: self-hosted
    #environment: production eeeeeeeeeeee 4
    permissions: read-all

    steps:
      - name: a
        run: git config --global url.https://${{ secrets.PAT }}@github.com/.insteadOf https://github.com/
      - name: Pull from repository
        run: git pull git@github.com:MalzaCAr/MaldaBot.git

      - uses: actions/checkout@v3

      

      - name: Run Container
        run: docker compose up -d --build
        env:
          TOKEN: ${{ secrets.DISCORD_TOKEN }}

      - name: Cleanup Unused Images
        run: docker image prune -f
